### ISSUE TITLE
GBStudio 2 ROMs Incompatible

### ISSUE THREAD

**Issue by maxoakland** [marcrobledo/super-game-boy-border-injector#1]
I know this was possibly expected, but it would be a great feature to add and one that would help me out since I'd love to release my games that aren't compatible with GBStudio 3 with SGB compatibility!

Here's a test ROM if interested: [WinkBetaTestROM.gb.zip](https://github.com/marcrobledo/super-game-boy-border-injector/files/14227914/WinkBetaTestROM.gb.zip)

![image](https://github.com/marcrobledo/super-game-boy-border-injector/assets/57502156/3c3f8e02-18d2-4f46-884d-d7022979d3e2)

**Comment by marcrobledo** [comment]
Looks like GB Studio do not use the common nop+jp entry point. But it was easy to fix :-D

Also, in order to allow emulators to show SGB border during CGB mode, I forced the injector to change the ROM's header.

So... happy to be able to say: this makes the injector fully compatible with GB Studio games!!

(make sure you are using v0.4 [see site footer], force a cache refresh just in case with Ctrl+F5)



Thank you for your contribution, can't wait to see your awesome game and other GB Studio games with beautiful SGB borders!

**Comment by maxoakland** [comment]
It works! Thanks for fixing it so quickly
